FROM arm64v8/mysql:8.0-oracle

# Set locale
RUN microdnf install -y \
    glibc-locale-source \
    glibc-langpack-ja \
    && microdnf clean all \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

COPY my.cnf /etc/mysql/conf.d/app.cnf
