LC_ALL=C.UTF-8
LANG=C.UTF-8
TERM="xterm-256color"
PATH=/usr/src/app/node_modules/.bin:$PATH

ZSH=$HOME/.oh-my-zsh

ZSH_DISABLE_COMPFIX=true
POWERLEVEL9K_DISABLE_RPROMPT=true

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_CONTEXT_TEMPLATE='%n'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='white'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context battery dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_SHORTEN_DIR_LENGTH=1

POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="white"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="white"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="white"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="red"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="yellow"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="black"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON='\uf74a'
POWERLEVEL9K_OS_ICON_BACKGROUND='202'
POWERLEVEL9K_CONTEXT_BACKGROUND='202'

plugins=(git zsh-syntax-highlighting zsh-completions)

source $ZSH/oh-my-zsh.sh
source $ZSH/custom/themes/powerlevel9k/powerlevel9k.zsh-theme
source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/custom/plugins/zsh-autopair/autopair.zsh
source $ZSH/custom/plugins/emoji-cli/emoji-cli.zsh

autopair-init
autoload -Uz compinit && compinit -i
autoload -U +X bashcompinit && bashcompinit

setopt no_beep
setopt nolistbeep
