FROM cypress/included:9.4.1

ENV LANG=ja_JP.UTF-8 \
    LC_CTYPE=ja_JP.UTF-8 \
    TZ=Asia/Tokyo \
    DBUS_SESSION_BUS_ADDRESS=/dev/null

WORKDIR /e2e

RUN apt-get update -qq && \
    apt-get install -y locales locales-all && \
    apt-get remove fonts-vlgothic && \
    apt-get install -y fonts-vlgothic && \
    locale-gen ja_JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP.utf8 && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*
