services:
  app:
    build:
      context: docker/app
    depends_on:
      - db
    volumes:
      - .:/var/www

  web:
    build:
      context: docker/web
    depends_on:
      - app
    ports:
      - 8000:80

  db:
    build:
      context: docker/db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
